### ISSUE TITLE
The library is not working. requires tensorflow

### ISSUE THREAD

**Issue by naprsa** [zendesk/min-tfs-client#47]
Hello! Thank you for this lightweight package. 
Apparently this is what I was looking for, but it seems that your library still requires the tensorflow package to be installed. Maybe there is a way to get around this?
Traceback (most recent call last):
  File "/Users/cupera/Work/karl_rc/experiments/grcp_predict.py", line 8, in <module>
    from min_tfs_client.requests import TensorServingClient
  File "/Users/cupera/.pyenv/versions/miniforge3-4.10.3-10/lib/python3.9/site-packages/min_tfs_client/requests.py", line 6, in <module>
    from tensorflow_serving.apis.classification_pb2 import ClassificationRequest, ClassificationResponse
  File "/Users/cupera/.pyenv/versions/miniforge3-4.10.3-10/lib/python3.9/site-packages/tensorflow_serving/apis/classification_pb2.py", line 16, in <module>
    from tensorflow_serving.apis import input_pb2 as tensorflow__serving_dot_apis_dot_input__pb2
  File "/Users/cupera/.pyenv/versions/miniforge3-4.10.3-10/lib/python3.9/site-packages/tensorflow_serving/apis/input_pb2.py", line 16, in <module>
    from tensorflow.core.example import example_pb2 as tensorflow_dot_core_dot_example_dot_example__pb2
ModuleNotFoundError: No module named 'tensorflow'
Thanks!

**Comment by leohoare** [comment]
It doesn't require Tensorflow and the library will generate these files.
How did you install the library?

- Pip from PyPi is the most straight forward method `pip install min-tfs-client`
- If you're installing from source code, don't forget to compile the protobuf 
```
git clone https://github.com/zendesk/min-tfs-client.git
cd min-tfs-client
python setup.py compile_pb copy_grpc
pip install .
```
https://pypi.org/project/min-tfs-client/
